version: "3.3"

services:
  web:
    build: .
    volumes:
      - .:/code
    expose:
      - 8000
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "81:80"
    depends_on:
      - web